### ISSUE TITLE
Вынести "мусор" в отдельный модуль CSS

### ISSUE THREAD

**Issue by TorinAsakura** [AtlantisUnited/opencart#1]
Вынеси свой срачь из https://github.com/AtlantisUnited/opencart/commit/8e6dedec9357415ff6445361ee54c2dafad732ef#diff-094b6c979a1cbc098c2e10085b4e8737R71

в надлежащий вид

**Comment by EclipticWld** [comment]
Clear aa0c523ebe829d3b79aebc39346c6a0fb7086821

**Comment by TorinAsakura** [comment]
Почистить, не?

**Comment by EclipticWld** [comment]
Reclean 145c7c9b06d0d4a463201edda96ef0f8bfe7320e
